---
title: "Childcare Cost Analysis"
subtitle: "INFO 526 - Project 1"
author:
  - name: "**Team InsightSquad** - Mohammad Farmani, Narasimha Vardhan Rachaputi, Amaan"
  - name: "Devendran, Shreemithra, Gowtham"
format: html
editor: visual
---

## Abstract

This data visualization project centers on unraveling patterns in tornado occurrences and their impacts across the United States. Tornadoes are violent, rotating columns of air that form severe thunderstorms capable of producing destructive winds. In this project we delve into two critical aspects: tornado magnitude patterns and the tornado related fatalities in each state . Through innovative visualizations like alley maps and horizontal bar plot, we seek to provide a clearer understanding of tornado phenomena, enabling informed decision-making and proactive disaster management.

## Introduction

The objective of this proposal is to explore the complex dynamics between childcare costs, unemployment rates, and poverty levels across various locations in the United States. By utilizing two main datasets—the National Database of Childcare Prices (NDCP) and a comprehensive Counties Dataset—we aim to uncover patterns and correlations that can inform us about any hidden relationship between these variables. The NDCP dataset, spanning from 2008 to 2018, offers an unparalleled look at childcare prices across the state level, categorized by provider type and age groups, while the Counties Dataset provides essential geographical and demographic insights.

## Questions

### Question 1: Which locations have lower unemployment rates? Which gender experiences higher unemployment rates in the US? Is there a relationship between the unemployment rate and poverty?

#### Introduction

This section outlines our methodology for investigating the relationships between unemployment rates, poverty levels, and childcare costs across the United States. By examining these variables, we aim to identify patterns that could have significant implications for social policy and economic support systems.

#### Approach

-   We will focus on the distribution of unemployment rates across genders and its relationship with poverty. The methodology includes creating spatial maps to visualize mean unemployment rates (overall, and by gender) across the US. We will then calculate the correlation between the overall unemployment rate and individual poverty levels at the state level, producing spatial maps to display these correlations.
-   For "Which locations have lower unemployment rates?", we will use the "unr_16" variable and the state IDs to plot the spatial map of the overall unemployment rate. We first average the mentioned variable over time, and then the averaged unemployment rate will be used to plot the spatial map.
-   For the second part, specifically gender-related, the "munr_16" and "funr_16" variables, as well as state location IDs, will be used to plot the unemployment rates for men and women, respectively. We first average the mentioned variables over time, and then the averaged unemployment rates will be used to plot the spatial map.
-   To quantify the relationship between the unemployment rate and poverty, the correlation between individual poverty, "pr_p", and overall unemployment, "unr_16", will be calculated for each state, and a spatial map will be plotted.

#### Analysis

#### Discussion

### Question 2: Which places have higher rates of family poverty? Is there a relationship between poverty and the cost of raising children?

#### Introduction

This section outlines our methodology for investigating the relationships between unemployment rates, poverty levels, and childcare costs across the United States. By examining these variables, we aim to identify patterns that could have significant implications for social policy and economic support systems.

#### Approach

-   The emphasis will be on understanding the dynamics between family poverty rates and the financial burden of childcare. This part involves generating spatial maps to illustrate the average rate of family poverty across the US. Subsequently, we will assess the correlation between family poverty rates and the cumulative childcare costs (encompassing both Family Childcare and Center-based Care) for all age groups at the state level, with spatial maps visualizing these correlations.
-   To illustrate the family poverty over US, the average of family poverty variable, pr_f, will be computed over the available time period, and then, the poverty of families will be plotted using the state IDs. Moreover, to demonstrate the relation between family poverty and children expenses, the sum of children costs , mc_infant, mc_toddler, mc_preschool, mfcc_infant, mfcc_toddler, and mfcc_preschool, will be calculated and the correlation between sum_of_children_costs and families' poverty will be computed and plotted.

#### Analysis

#### Discussion

The proposed analysis plan is designed to dissect the intricate web of economic factors influencing family well-being and child-rearing costs. By delving into the spatial and statistical relationships between unemployment, poverty, and childcare expenses, we anticipate uncovering regional disparities and potential areas for policy intervention. The findings from this analysis could provide a robust evidence base for developing targeted strategies to alleviate the economic pressures on families, particularly in regions where the burden of childcare costs significantly intersects with high unemployment and poverty rates. Through this investigation, we aim to contribute to the broader dialogue on enhancing economic security and access to quality childcare, thereby supporting the well-being of families across the United States.
